version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.4.2"
    # TF_COMMAND: "apply"
    TF_COMMAND: "destroy"
  paramater-store:
    AWS_ACCESS_KEY_ID: "/CodeBuild/MY_AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "/CodeBuild/AWS_SECRET_ACCESS_KEY"

phases:
  install:
    runtime-versions:
      python: 3.9
    on-failure: ABORT
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin
  pre_build:
    on-failure: ABORT
    commands:
      - echo terraform execution started on `date`
  build:
    on-failure: ABORT
    commands:
      - cd "$CODEBUILD_SRC_DIR/terraform-manifests"
      - ls -lrt "$CODEBUILD_SRC_DIR/terraform-manifests"
      - terraform --version
      - echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY 
      - aws sts get-caller-identity
      - terraform init -input=false --backend-config=dev.conf
      - terraform fmt
      - terraform validate
      - terraform plan -input=false -lock=false -var-file=dev.tfvars
      - terraform $TF_COMMAND -input=false -var-file=dev.tfvars -auto-approve

  post_build:
    on-failure: CONTINUE
    commands:
      - echo terraform execution ended on `date`